name: "Build"
permissions: {}

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  build:
    strategy:
      matrix:
        module: [oniguruma-jni, oniguruma-ffm]
    uses: ./.github/workflows/build.yaml
    with:
      module: ${{ matrix.module }}
